const products = [
  {
    id: 1,
    price: 25,
    img: "Ail",
    name: "Ail - 1kg",
    category: "légumes",
  },
  {
    id: 2,
    price: 45,
    img: "Banane",
    name: "Banane - 5kg",
    category: "fruits",
  },
  {
    id: 3,
    price: 10.5,
    img: "Carotte",
    name: "Carotte - 3kg",
    category: "légumes",
  },
  {
    id: 4,
    price: 5,
    img: "Celeri",
    name: "Céléri - 1kg",
    category: "légumes",
  },
  {
    id: 5,
    price: 25.5,
    img: "Champignon",
    name: "Champignon - 1kg",
    category: "légumes",
  },
  {
    id: 6,
    price: 40,
    img: "Fraise",
    name: "Fraise - 2kg",
    category: "fruits",
  },
  {
    id: 7,
    price: 25,
    img: "Kiwi",
    name: "Kiwi - 1kg",
    category: "fruits",
  },
  {
    id: 8,
    price: 41.25,
    img: "Mangue",
    name: "Mangue - 4kg",
    category: "fruits",
  },
  {
    id: 9,
    price: 15,
    img: "Melon",
    name: "Melon - 2kg",
    category: "fruits",
  },
  {
    id: 10,
    price: 20.1,
    img: "Oignon",
    name: "Oignon - 5kg",
    category: "légumes",
  },
  {
    id: 11,
    price: 14.6,
    img: "Orange",
    name: "Orange - 4kg",
    category: "fruits",
  },
  {
    id: 12,
    price: 40,
    img: "Pasteque",
    name: "Pastèque - 5kg",
    category: "fruits",
  },
  {
    id: 13,
    price: 5.5,
    img: "Persil",
    name: "Persil - 3kg",
    category: "légumes",
  },
  {
    id: 14,
    price: 6,
    img: "Poireau",
    name: "Poireau - 3kg",
    category: "légumes",
  },
  {
    id: 15,
    price: 25,
    img: "Poivron",
    name: "Poivron - 5kg",
    category: "légumes",
  },
  {
    id: 16,
    price: 15,
    img: "Pomme",
    name: "Pomme - 6kg",
    category: "fruits",
  },
  {
    id: 17,
    price: 50,
    img: "Raisin",
    name: "Raisin - 5kg",
    category: "fruits",
  },
  {
    id: 18,
    price: 13,
    img: "Tomate",
    name: "Tomate - 3kg",
    category: "légumes",
  },
];

export default products;
